In [1]:
import numpy as np

In [2]:
#Creating ndarrays using numpy
#They are faster than a python list
# nd means an array of n dimensions

a= np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#Also, you can't do this
b= np.array(1,2,3)

#TypeError: array() takes from 1 to 2 positional arguments but 3 were given
#So yeah one of those positional argument things

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
#We can also reshape our array!
c=np.array([1,2,3,3,5,4]).reshape(2,3)
c #Meaning 2 parts containing 3 elements each

array([[1, 2, 3],
       [3, 5, 4]])

In [ ]:
d=np.array([2,3,4,5,6,7,3,4]).reshape(2,2,2)
d #Meaning 2 big parts in which two small parts will be there in which two elements will reside in each part respectively.


array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [3, 4]]])

In [ ]:
#performing various operations on numpy arrays

e= np.array([1,2,3,4,5,5,6])
print(e.sum()) #Sums up the entire array
print(e.mean()) #Calculates the arithmatic mean of the array
print(e.min()) #Shows the smallest value element in the array
print(e.max()) #Shows the max element in the array

26
3.7142857142857144
1
6


### Special NumPy Arrays

These are some useful arrays that you can quickly create in NumPy. Don't worry too much about learning them now but it'll be useful to have a cheatsheet of them nearby.

In [ ]:
np.zeros(5) #Will create an array which will contain 5 zeroes
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000
np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])